### ISSUE TITLE
Build from .tar.gz sources once flytekit sourc includes package data

### ISSUE THREAD

**Issue by asford** [conda-forge/flytekit-feedstock#16]
## Reason for Build Failure: `1/N`

There is a file, `template.html` that is not found in the pypi source. This needs fixing the upstream repository by: 
- adding this `template.html` file to `MANIFEST.in` if somehow it is unavailable in the pypi source
- fixing jinja2 template loading with `autoescaping`

See: https://github.com/flyteorg/flytekit/pull/1088

- https://github.com/sugatoray/flytekit/blob/fix_jinja_template/flytekit/deck/html/template.html

```sh
1102 jinja2.exceptions.TemplateNotFound: template.html
```

[(error)](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=530152&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=1102)

Some of the places in the code where `template.html` is called from.

- `jinja2/loaders.py`: 
  
  ```python
  raise TemplateNotFound(template)
  ```

- errors originating from `flytekit`:

  ```python
  import flytekit
  
  # flytekit/__init__.py", line 164, in <module>
  from flytekit.core.base_sql_task import SQLTask
  
  # flytekit/core/base_sql_task.py", line 4, in <module>
  from flytekit.core.base_task import PythonTask, TaskMetadata
  
  # flytekit/core/base_task.py", line 42, in <module>
  from flytekit.deck.deck import Deck
  
  # flytekit/deck/__init__.py", line 1, in <module>
  from .deck import Deck

  # flytekit/deck/deck.py", line 115, in <module>
  template = env.get_template("template.html")
  ```

<details>
<summary>See Error Details | <b>Time Elasped</b>: <code>3:57</code> s</summary>
<p>

```sh
import: 'flytekit'
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/flytekit_1656731293461/test_tmp/run_test.py", line 2, in <module>
    import flytekit
  File "/home/conda/feedstock_root/build_artifacts/flytekit_1656731293461/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.10/site-packages/flytekit/__init__.py", line 164, in <module>
    from flytekit.core.base_sql_task import SQLTask
  File "/home/conda/feedstock_root/build_artifacts/flytekit_1656731293461/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.10/site-packages/flytekit/core/base_sql_task.py", line 4, in <module>
    from flytekit.core.base_task import PythonTask, TaskMetadata
  File "/home/conda/feedstock_root/build_artifacts/flytekit_1656731293461/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.10/site-packages/flytekit/core/base_task.py", line 42, in <module>
    from flytekit.deck.deck import Deck
  File "/home/conda/feedstock_root/build_artifacts/flytekit_1656731293461/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.10/site-packages/flytekit/deck/__init__.py", line 1, in <module>
    from .deck import Deck
  File "/home/conda/feedstock_root/build_artifacts/flytekit_1656731293461/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.10/site-packages/flytekit/deck/deck.py", line 115, in <module>
    template = env.get_template("template.html")
  File "/home/conda/feedstock_root/build_artifacts/flytekit_1656731293461/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/conda/feedstock_root/build_artifacts/flytekit_1656731293461/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/conda/feedstock_root/build_artifacts/flytekit_1656731293461/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/conda/feedstock_root/build_artifacts/flytekit_1656731293461/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.10/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: template.html
Tests failed for flytekit-1.1.0-pyhd8ed1ab_0.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
WARNING:conda_build.build:Tests failed for flytekit-1.1.0-pyhd8ed1ab_0.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
TESTS FAILED: flytekit-1.1.0-pyhd8ed1ab_0.tar.bz2
```

</p>
</details>

_Originally posted by @sugatoray in https://github.com/conda-forge/flytekit-feedstock/issues/14#issuecomment-1172955010_

**Comment by asford** [comment]
Closed in #27
